# Generated by Django 2.1.5 on 2019-11-30 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Pricing',
        ),
    ]
