# Generated by Django 2.1.5 on 2019-11-30 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191130_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.DeleteModel(
            name='Pricing',
        ),
    ]
