# Generated by Django 2.1.5 on 2019-11-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricing',
            new_name='Price',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.ManyToManyField(blank=True, to='orders.Price'),
        ),
    ]
