# Generated by Django 2.1.5 on 2019-11-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191130_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='item_pizza',
            new_name='pizza',
        ),
    ]
