# Generated by Django 2.1.5 on 2019-11-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191130_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='pricing',
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ManyToManyField(blank=True, to='orders.Price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.ManyToManyField(blank=True, related_name='price', to='orders.Price'),
        ),
    ]
