# Generated by Django 2.1.5 on 2019-12-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='special',
        ),
    ]
