# Generated by Django 2.1.5 on 2019-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20191201_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
