# Generated by Django 2.1.5 on 2019-12-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_dinnerplatter_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='size',
        ),
    ]
