# Generated by Django 2.1.5 on 2019-12-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_pizza_num_toppings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='num_toppings',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'One'), (2, 'Two'), (3, 'Three')], default=0),
        ),
    ]
