# Generated by Django 2.1.5 on 2019-12-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20191205_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasta',
            name='size',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='size',
        ),
        migrations.AddField(
            model_name='sub',
            name='additions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Addition'),
        ),
    ]
