# Generated by Django 2.1.5 on 2019-12-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20191206_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.5, max_digits=5),
        ),
    ]
