# Generated by Django 2.1.5 on 2019-12-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20191206_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='special',
        ),
    ]
