# Generated by Django 2.1.5 on 2019-12-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_remove_order_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qty_dplatter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qty_pasta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qty_pizza',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qty_salad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qty_sub',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
