# Generated by Django 2.1.5 on 2019-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20191206_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty_dplatter',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty_pasta',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty_pizza',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty_salad',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='qty_sub',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
