# Generated by Django 2.1.5 on 2019-12-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20191206_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='additions',
        ),
    ]
