# Generated by Django 2.1.5 on 2019-12-07 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_remove_sub_additions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addition',
            old_name='addition',
            new_name='category',
        ),
    ]
