# Generated by Django 2.1.5 on 2020-01-04 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_order_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_by',
        ),
    ]
